# Server config
[server]
host = "localhost"
port = "8001"
#certfile = "${AUTHORIZR_PROXY_CERT_FILE_PATH}"
#keyfile = "${AUTHORIZR_PROXY_KEY_FILE_PATH}"
worker-host = "http://localhost:8000"

# Logger
[logger]
type = "default" #If not specified default is StdOut
#type = "file" #If not specified default is StdOut
level = "debug"
	# Directory for file configuration
	[logger.file]
	dir = "/tmp/authorizr/proxy.log"

# Resources definition example
[[resources]]
    id = "resource1"
    host = "https://httpbin.org/"
    url = "/get"
    method = "GET"
    urn = "urn:ews:example:instance1:resource/get"
    action = "example:get"
[[resources]]
    id = "resource2"
    host = "https://httpbin.org/"
    url = "/status/:code"
    method = "GET"
    urn = "urn:ews:example:instance1:resource/status/{code}"
    action = "example:getCode"
[[resources]]
    id = "resource3"
    host = "https://httpbin.org/"
    url = "/post"
    method = "POST"
    urn = "urn:ews:example:instance1:resource/post"
    action = "example:post"

