FROM alpine
MAINTAINER Tecsisa

USER root
RUN apk update && apk add ca-certificates
# Proxy
COPY bin/proxy /go/bin/proxy
COPY dist/proxy_env_vars.toml /proxy_env_vars.toml

ADD scripts/docker/entrypoint.sh /go/bin/entrypoint.sh
RUN chmod 750 /go/bin/*

EXPOSE 8000 8001

ENTRYPOINT ["/go/bin/entrypoint.sh", "-p"]
